apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-de-graos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor-de-graos
  template:
    metadata:
      labels:
        app: produtor-de-graos
    spec:
      containers:
      - name: produtor-de-graos
        image: thiagogmta/produtor-de-graos:latest
        ports:
        - containerPort: 50051

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-de-agua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor-de-agua
  template:
    metadata:
      labels:
        app: produtor-de-agua
    spec:
      containers:
      - name: produtor-de-agua
        image: thiagogmta/produtor-de-agua:latest
        ports:
        - containerPort: 50052

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-de-farinha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor-de-farinha
  template:
    metadata:
      labels:
        app: produtor-de-farinha
    spec:
      containers:
      - name: produtor-de-farinha
        image: thiagogmta/produtor-de-farinha:latest
        ports:
        - containerPort: 50053

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produtor-de-pao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produtor-de-pao
  template:
    metadata:
      labels:
        app: produtor-de-pao
    spec:
      containers:
      - name: produtor-de-pao
        image: thiagogmta/produtor-de-pao:latest
        ports:
        - containerPort: 50054
