# Deployment para client_carga_simples
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-carga-simples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-carga-simples
  template:
    metadata:
      labels:
        app: client-carga-simples
    spec:
      containers:
      - name: client-carga-simples
        image: thiagogmta/client_carga_simples:latest
